# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import CNC.choosetype , CNC.BasicPara , CNC.DetailPara
class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(500, 360)
        Wizard.setLayoutDirection(QtCore.Qt.LeftToRight)
        Wizard.setSizeGripEnabled(False)
        Wizard.setModal(False)
        Wizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        self.choosetype = CNC.choosetype.ChooseType()
        self.choosetype.setObjectName("choosetype")
        # self.choosetype = QtWidgets.QWizardPage()
        # self.choosetype.setObjectName("choosetype")
        # self.widget = QtWidgets.QWidget(self.choosetype)
        # self.widget.setGeometry(QtCore.QRect(-10, 70, 401, 51))
        # self.widget.setObjectName("widget")
        # self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        # self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout_7.setObjectName("gridLayout_7")
        # self.TypeLabel = QtWidgets.QLabel(self.widget)
        # self.TypeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.TypeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        # self.TypeLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        # self.TypeLabel.setMidLineWidth(0)
        # self.TypeLabel.setObjectName("TypeLabel")
        # self.gridLayout_7.addWidget(self.TypeLabel, 0, 0, 1, 1)
        # self.comboBox = QtWidgets.QComboBox(self.widget)
        # self.comboBox.setObjectName("comboBox")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.gridLayout_7.addWidget(self.comboBox, 0, 1, 1, 1)
        Wizard.addPage(self.choosetype)
        self.basicpara = CNC.BasicPara.BasicPara()
        # self.basicpara.setEnabled(True)
        # self.basicpara.setMinimumSize(QtCore.QSize(0, 121))
        # self.basicpara.setObjectName("basicpara")
        # self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.basicpara)
        # self.verticalLayout_2.setObjectName("verticalLayout_2")
        # self.gridLayout_2 = QtWidgets.QGridLayout()
        # self.gridLayout_2.setObjectName("gridLayout_2")
        # self.gridLayout = QtWidgets.QGridLayout()
        # self.gridLayout.setObjectName("gridLayout")
        # self.CompenSpin = QtWidgets.QSpinBox(self.basicpara)
        # self.CompenSpin.setObjectName("CompenSpin")
        # self.gridLayout.addWidget(self.CompenSpin, 1, 1, 1, 1)
        # self.FeedLabel = QtWidgets.QLabel(self.basicpara)
        # self.FeedLabel.setObjectName("FeedLabel")
        # self.gridLayout.addWidget(self.FeedLabel, 1, 3, 1, 1)
        # self.FeedText = QtWidgets.QLineEdit(self.basicpara)
        # self.FeedText.setObjectName("FeedText")
        # self.gridLayout.addWidget(self.FeedText, 1, 4, 1, 1)
        # self.CoordinateText = QtWidgets.QLineEdit(self.basicpara)
        # self.CoordinateText.setObjectName("CoordinateText")
        # self.gridLayout.addWidget(self.CoordinateText, 0, 4, 1, 1)
        # self.CompenLabel = QtWidgets.QLabel(self.basicpara)
        # self.CompenLabel.setObjectName("CompenLabel")
        # self.gridLayout.addWidget(self.CompenLabel, 1, 0, 1, 1)
        # self.CutterSpin = QtWidgets.QSpinBox(self.basicpara)
        # self.CutterSpin.setWrapping(False)
        # self.CutterSpin.setObjectName("CutterSpin")
        # self.gridLayout.addWidget(self.CutterSpin, 0, 1, 1, 1)
        # self.CutterLabel = QtWidgets.QLabel(self.basicpara)
        # self.CutterLabel.setObjectName("CutterLabel")
        # self.gridLayout.addWidget(self.CutterLabel, 0, 0, 1, 1)
        # self.CorrdinateLabel = QtWidgets.QLabel(self.basicpara)
        # self.CorrdinateLabel.setObjectName("CorrdinateLabel")
        # self.gridLayout.addWidget(self.CorrdinateLabel, 0, 3, 1, 1)
        # spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        # spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        # self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        # self.RevolvingLabel = QtWidgets.QLabel(self.basicpara)
        # self.RevolvingLabel.setObjectName("RevolvingLabel")
        # self.gridLayout_2.addWidget(self.RevolvingLabel, 1, 0, 1, 1)
        # self.RevolvingText = QtWidgets.QLineEdit(self.basicpara)
        # self.RevolvingText.setObjectName("RevolvingText")
        # self.gridLayout_2.addWidget(self.RevolvingText, 1, 1, 1, 1)
        # self.verticalLayout_2.addLayout(self.gridLayout_2)
        Wizard.addPage(self.basicpara)
        self.Detailpara = CNC.DetailPara.DetailPara()
        # self.Detailpara.setObjectName("Detailpara")
        # self.widget1 = QtWidgets.QWidget(self.Detailpara)
        # self.widget1.setGeometry(QtCore.QRect(0, 0, 471, 291))
        # self.widget1.setObjectName("widget1")
        # self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        # self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout_3.setObjectName("gridLayout_3")
        # self.SubBox = QtWidgets.QGroupBox(self.widget1)
        # self.SubBox.setObjectName("SubBox")
        # self.widget2 = QtWidgets.QWidget(self.SubBox)
        # self.widget2.setGeometry(QtCore.QRect(10, 40, 440, 60))
        # self.widget2.setObjectName("widget2")
        # self.gridLayout_6 = QtWidgets.QGridLayout(self.widget2)
        # self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout_6.setObjectName("gridLayout_6")
        # self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.SubDiaLabel = QtWidgets.QLabel(self.widget2)
        # self.SubDiaLabel.setObjectName("SubDiaLabel")
        # self.horizontalLayout_2.addWidget(self.SubDiaLabel)
        # self.SubDiaText = QtWidgets.QLineEdit(self.widget2)
        # self.SubDiaText.setObjectName("SubDiaText")
        # self.horizontalLayout_2.addWidget(self.SubDiaText)
        # self.SubLongLabel = QtWidgets.QLabel(self.widget2)
        # self.SubLongLabel.setObjectName("SubLongLabel")
        # self.horizontalLayout_2.addWidget(self.SubLongLabel)
        # self.SubLongText = QtWidgets.QLineEdit(self.widget2)
        # self.SubLongText.setObjectName("SubLongText")
        # self.horizontalLayout_2.addWidget(self.SubLongText)
        # self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        # self.SubArcLabel = QtWidgets.QLabel(self.widget2)
        # self.SubArcLabel.setObjectName("SubArcLabel")
        # self.gridLayout_6.addWidget(self.SubArcLabel, 1, 0, 1, 1)
        # self.SubArcText = QtWidgets.QLineEdit(self.widget2)
        # self.SubArcText.setObjectName("SubArcText")
        # self.gridLayout_6.addWidget(self.SubArcText, 1, 1, 1, 1)
        # self.gridLayout_3.addWidget(self.SubBox, 1, 0, 1, 1)
        # self.MainBox = QtWidgets.QGroupBox(self.widget1)
        # self.MainBox.setObjectName("MainBox")
        # self.widget3 = QtWidgets.QWidget(self.MainBox)
        # self.widget3.setGeometry(QtCore.QRect(10, 30, 440, 91))
        # self.widget3.setObjectName("widget3")
        # self.gridLayout_5 = QtWidgets.QGridLayout(self.widget3)
        # self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout_5.setObjectName("gridLayout_5")
        # self.gridLayout_4 = QtWidgets.QGridLayout()
        # self.gridLayout_4.setObjectName("gridLayout_4")
        # self.MainLabel = QtWidgets.QLabel(self.widget3)
        # self.MainLabel.setObjectName("MainLabel")
        # self.gridLayout_4.addWidget(self.MainLabel, 0, 0, 1, 1)
        # self.MainText = QtWidgets.QLineEdit(self.widget3)
        # self.MainText.setObjectName("MainText")
        # self.gridLayout_4.addWidget(self.MainText, 0, 1, 1, 1)
        # self.LongLabel = QtWidgets.QLabel(self.widget3)
        # self.LongLabel.setObjectName("LongLabel")
        # self.gridLayout_4.addWidget(self.LongLabel, 0, 2, 1, 1)
        # self.LongText = QtWidgets.QLineEdit(self.widget3)
        # self.LongText.setObjectName("LongText")
        # self.gridLayout_4.addWidget(self.LongText, 0, 3, 1, 1)
        # self.ChamferLabel1 = QtWidgets.QLabel(self.widget3)
        # self.ChamferLabel1.setObjectName("ChamferLabel1")
        # self.gridLayout_4.addWidget(self.ChamferLabel1, 1, 0, 1, 1)
        # self.ChamferText1 = QtWidgets.QLineEdit(self.widget3)
        # self.ChamferText1.setObjectName("ChamferText1")
        # self.gridLayout_4.addWidget(self.ChamferText1, 1, 1, 1, 1)
        # self.ChamferLabel2 = QtWidgets.QLabel(self.widget3)
        # self.ChamferLabel2.setObjectName("ChamferLabel2")
        # self.gridLayout_4.addWidget(self.ChamferLabel2, 1, 2, 1, 1)
        # self.ChamferText2 = QtWidgets.QLineEdit(self.widget3)
        # self.ChamferText2.setObjectName("ChamferText2")
        # self.gridLayout_4.addWidget(self.ChamferText2, 1, 3, 1, 1)
        # self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        # self.ArcLabel = QtWidgets.QLabel(self.widget3)
        # self.ArcLabel.setObjectName("ArcLabel")
        # self.gridLayout_5.addWidget(self.ArcLabel, 1, 0, 1, 1)
        # self.ArcText = QtWidgets.QLineEdit(self.widget3)
        # self.ArcText.setObjectName("ArcText")
        # self.gridLayout_5.addWidget(self.ArcText, 1, 1, 1, 1)
        # self.gridLayout_3.addWidget(self.MainBox, 0, 0, 1, 1)
        Wizard.addPage(self.Detailpara)

        self.retranslateUi(Wizard)

        #self.choosetype..connect(self.choosetypenext)

        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "工件编辑"))
        # self.choosetype.setTitle(_translate("Wizard", "请选择加工工件"))
        # self.choosetype.setSubTitle(_translate("Wizard", "主轴颈 | 连杆颈"))
        # self.TypeLabel.setText(_translate("Wizard", "<html><head/><body><p align=\"right\">工件类型：</p></body></html>"))
        # self.comboBox.setItemText(0, _translate("Wizard", "主轴颈一"))
        # self.comboBox.setItemText(1, _translate("Wizard", "主轴颈二"))
        # self.comboBox.setItemText(2, _translate("Wizard", "连杆颈"))
        # self.basicpara.setTitle(_translate("Wizard", "基础参数"))
        # self.basicpara.setSubTitle(_translate("Wizard", "刀具选择 | 进给 | 转速"))
        # self.FeedLabel.setText(_translate("Wizard", "进给(mm/r)"))
        # self.CompenLabel.setText(_translate("Wizard", "刀补"))
        # self.CutterLabel.setText(_translate("Wizard", "刀具"))
        # self.CorrdinateLabel.setText(_translate("Wizard", "起始坐标(x,y)"))
        # self.RevolvingLabel.setText(_translate("Wizard", "主轴转速（r/min)"))
        # self.SubBox.setTitle(_translate("Wizard", "连杆颈"))
        # self.SubDiaLabel.setText(_translate("Wizard", "连杆颈直径"))
        # self.SubLongLabel.setText(_translate("Wizard", "连杆颈宽"))
        # self.SubArcLabel.setText(_translate("Wizard", "圆弧(半径 宽度 角度 )"))
        # self.MainBox.setTitle(_translate("Wizard", "主轴颈"))
        # self.MainLabel.setText(_translate("Wizard", "主轴(直径 长度)"))
        # self.LongLabel.setText(_translate("Wizard", "长轴(直径 长度)"))
        # self.ChamferLabel1.setText(_translate("Wizard", "倒角一(角度 宽度)"))
        # self.ChamferLabel2.setText(_translate("Wizard", "倒角二(角度 宽度)"))
        # self.ArcLabel.setText(_translate("Wizard", "圆弧(半径 宽度 角度 )"))



    def choosetypenext(self):
        self.CoordinateText.setText("hello")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wizard = QtWidgets.QWizard()
    ui = Ui_Wizard()
    ui.setupUi(Wizard)
    Wizard.show()
    sys.exit(app.exec_())

